#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := mqtt_logic_producer_esp32

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../esp-google-iot

include $(IDF_PATH)/make/project.mk